In [ ]:
!git clone https://github.com/Mahdi-Abdollahii/AstroDC.git

Cloning into 'AstroDC'...
remote: Enumerating objects: 131, done.
remote: Counting objects: 100% (131/131), done.
remote: Compressing objects: 100% (121/121), done.
remote: Total 131 (delta 59), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (131/131), 780.88 KiB | 2.13 MiB/s, done.
Resolving deltas: 100% (59/59), done.

In [ ]:
pip install git+https://github.com/Mahdi-Abdollahii/AstroDC.git

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/Mahdi-Abdollahii/AstroDC.git
  Cloning https://github.com/Mahdi-Abdollahii/AstroDC.git to /tmp/pip-req-build-s0fyw371
  Running command git clone -q https://github.com/Mahdi-Abdollahii/AstroDC.git /tmp/pip-req-build-s0fyw371
Building wheels for collected packages: AstroDC
  Building wheel for AstroDC (setup.py) ... done
  Created wheel for AstroDC: filename=AstroDC-1.0.2-py3-none-any.whl size=1900 sha256=2c17ed28a19157d7357df51e9f3486b87aa9ffb48b9fd4d2ee4739a8200ff472
  Stored in directory: /tmp/pip-ephem-wheel-cache-qho55fxh/wheels/17/fd/82/87725e59615f2b1930570f31c0dbcb8c6142c140afad8decc3
Successfully built AstroDC
Installing collected packages: AstroDC
Successfully installed AstroDC-1.0.2

In [ ]:
from astropy import units as u
from astropy.coordinates import SkyCoord
from astropy.table import Table
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from AstroDC import AstroDC

In [ ]:
result = pd.read_csv ("/content/drive/MyDrive/IPM-ASTOPHYSICS/Observational Astronomy/NGC 6822/Data/bar_catalogue.csv")
data_Nan = result.replace(r'^\s*$', np.nan, regex=True)
Main_cat = data_Nan.fillna(89.9999)

In [ ]:
Main_cat

,mid,Id-main,ra,dec,J,eJ,H,eH,Ks,eKs,Types
0,1,10042,19:44:43.81,-14:46:10.7,14.179,0.014,13.352,0.030,13.029,0.035,RSGs
1,2,40085,19:44:45.98,-14:51:02.4,15.556,0.023,14.709,0.019,14.476,0.020,RSGs
2,3,10186,19:44:47.13,-14:46:27.1,16.132,0.020,15.281,0.021,15.038,0.020,RSGs
3,4,10164,19:44:50.54,-14:48:01.6,15.772,0.012,14.942,0.013,14.716,0.016,RSGs
4,5,10157,19:44:51.64,-14:48:58.0,15.864,0.017,14.928,0.014,14.665,0.015,RSGs
...,...,...,...,...,...,...,...,...,...,...,...
685,686,11029,296.28308,-14.80497,17.460,0.030,16.550,0.020,16.220,0.050,S
686,687,11004,296.27341,-14.80861,17.600,0.030,16.620,0.030,16.270,0.050,S
687,688,10784,296.21545,-14.83469,17.450,0.030,16.530,0.040,16.200,0.060,S
688,689,10326,296.25522,-14.82579,16.820,0.030,15.860,0.030,15.520,0.020,S
689,690,12050,296.25427,-14.81764,18.170,0.070,17.250,0.100,16.700,0.050,S

In [ ]:
AstroDC.Vizier_XMLCSV_to_CSV("/content/drive/MyDrive/IPM-ASTOPHYSICS/Observational Astronomy/NGC 6822/Data/Kang_2006_1.tsv","Kang_2006_1")
AstroDC.Vizier_XMLCSV_to_CSV("/content/drive/MyDrive/IPM-ASTOPHYSICS/Observational Astronomy/NGC 6822/Data/Kang_2006_2.tsv","Kang_2006_2")

Kang_2006_1.csv file of this data saved in local directory.
Kang_2006_2.csv file of this data saved in local directory.

In [ ]:
Kang_2006_1 = pd.read_csv ('/content/Kang_2006_1.csv').replace(r'^\s*$', np.nan, regex=True)
Kang_2006_2 = pd.read_csv ('/content/Kang_2006_2.csv').replace(r'^\s*$', np.nan, regex=True)

Kang_2006_1 = Kang_2006_1.fillna(89.9999)
Kang_2006_2 = Kang_2006_2.fillna(89.9999)

In [ ]:
Scnd_cat = Kang_2006_1
Main_cat_Coord = SkyCoord(Main_cat['ra'], Main_cat['dec'], unit=(u.hourangle, u.deg))
Scnd_cat_Coord = SkyCoord(Scnd_cat['RAJ2000("h:m:s")'], Scnd_cat['DEJ2000("d:m:s")'], unit=(u.hourangle, u.deg))

In [ ]:
idx, d2D, d3D = Scnd_cat_Coord.match_to_catalog_sky(Main_cat_Coord)

In [ ]:
max_sep = 1.0 * u.arcsec        # Maximum erorr
i_OK = d2D < max_sep

In [ ]:
Secondary_catalog = Scnd_cat[i_OK]
Main_catalog = Main_cat.iloc[idx[i_OK]]

In [ ]:
Secondary_catalog.to_csv(r'Secondary_catalog.csv', header=True, index=None, sep='\t', mode='w')
Main_catalog.to_csv(r'Main_catalog.csv', header=True, index=None, sep='\t', mode='w')

In [ ]:
with open("Main_catalog.csv") as f1, open("Secondary_catalog.csv") as f2, open("X_Catalog.csv", "w") as f3:
     for x, y in zip(f1, f2):
          f3.write(x.strip() + '\t' + y.strip() + '\n')
f1.close()
f2.close()
f3.close()

In [ ]:
X_data = pd.read_csv ("X_Catalog.csv", sep = '\t')
X_data

,mid,Id-main,ra,dec,J,eJ,H,eH,Ks,eKs,Types,Seq( ),"RAJ2000(""h:m:s"")","DEJ2000(""d:m:s"")",Kmag(mag),J-K(mag),H-K(mag),gmag(mag),g-i(mag)
0,206,10282,19:44:48.7416,-14:48:40.788,17.52,0.05,16.61,0.03,16.18,0.04,non,6.0,19 44 48.76,-14 48 40.3,16.150,1.367,0.550,22.550,2.703
1,207,10283,19:44:48.7392,-14:49:20.208,18.00,0.05,17.09,0.03,16.68,0.06,non,7.0,19 44 48.78,-14 49 20.2,16.677,1.323,0.472,22.230,0.347
2,220,10297,19:44:49.2216,-14:45:37.044,16.81,0.07,15.83,0.04,15.35,0.03,non,17.0,19 44 49.21,-14 45 36.3,15.448,1.385,0.514,22.292,3.058
3,221,10298,19:44:49.2048,-14:49:42.276,17.58,0.05,16.60,0.06,16.24,0.05,non,19.0,19 44 49.23,-14 49 41.7,16.282,1.340,0.405,22.248,2.369
4,232,10309,19:44:49.9872,-14:47:50.352,17.74,0.06,16.82,0.04,16.41,0.03,non,39.0,19 44 50.01,-14 47 50.0,16.417,1.278,0.443,22.489,2.453
5,47,12751,19:44:50.4648,-14:45:35.028,17.89,9.99,16.91,9.99,16.29,9.99,LPVs,49.0,19 44 50.46,-14 45 34.2,16.479,1.299,0.487,24.233,3.334

In [ ]:
Kang_2006_2

,Seq( ),"RAJ2000(""h:m:s"")","DEJ2000(""d:m:s"")",Kmag(mag),J-K(mag),H-K(mag),gmag(mag),g-i(mag),R-I(mag),[LDB2002]()
0,1.0,19 44 48.60,-14 49 03.5,16.022,2.141,0.790,23.466,3.443,1.679,277.0000
1,2.0,19 44 48.92,-14 47 37.6,15.516,1.793,0.755,24.070,3.889,1.59,285.0000
2,3.0,19 44 49.14,-14 49 50.8,15.007,1.833,0.716,23.215,3.857,1.61,293.0000
3,4.0,19 44 49.17,-14 45 45.5,16.052,1.623,0.592,22.756,2.512,1.407,295.0000
4,5.0,19 44 49.26,-14 46 35.0,15.373,1.914,0.816,23.428,3.440,1.611,300.0000
5,6.0,19 44 49.30,-14 44 59.4,15.966,1.591,0.639,23.570,3.341,1.356,301.0000
6,7.0,19 44 49.33,-14 48 46.1,15.437,1.947,0.765,23.608,3.603,1.524,302.0000
7,8.0,19 44 49.72,-14 44 41.8,15.480,1.646,0.616,23.113,3.369,1.487,307.0000
8,9.0,19 44 50.08,-14 44 39.3,15.764,1.571,0.613,23.287,3.292,1.304,310.0000
9,10.0,19 44 50.34,-14 45 35.9,16.266,1.786,0.793,23.564,3.371,1.422,315.0000
10,11.0,19 44 50.52,-14 48 47.3,15.783,1.599,0.603,22.611,2.851,1.278,317.0000
11,12.0,19 44 50.63,-14 48 55.2,15.662,1.818,0.727,22.584,2.705,1.342,321.0000
12,13.0,19 44 50.65,-14 44 59.8,17.178,1.598,0.677,23.624,2.505,89.9999,89.9999
13,14.0,19 44 50.67,-14 47 34.5,16.146,1.604,0.588,22.948,2.784,89.9999,89.9999
14,15.0,19 44 50.76,-14 48 40.9,15.442,1.708,0.642,22.788,3.105,1.396,322.0000
15,16.0,19 44 50.98,-14 46 27.8,15.786,1.781,0.793,22.843,3.247,1.544,325.0000
16,17.0,19 44 51.02,-14 48 05.1,16.119,2.734,1.192,23.805,0.044,89.9999,89.9999
17,18.0,19 44 51.67,-14 48 33.7,15.377,2.096,0.840,24.022,3.760,1.721,340.0000
18,19.0,19 44 51.82,-14 48 49.1,15.520,2.046,0.865,23.948,3.660,1.633,344.0000
19,20.0,19 44 51.89,-14 47 46.1,15.427,1.866,0.797,24.483,4.282,89.9999,89.9999
20,21.0,19 44 51.96,-14 44 19.0,16.835,2.053,0.795,22.983,2.284,89.9999,89.9999
21,22.0,19 44 52.05,-14 48 40.1,15.369,1.912,0.747,23.790,3.622,1.675,348.0000
22,23.0,19 44 52.05,-14 49 22.4,15.526,1.697,0.683,22.746,2.746,89.9999,89.9999
23,24.0,19 44 52.08,-14 47 48.0,15.696,1.830,0.785,23.812,3.794,1.596,349.0000
24,25.0,19 44 52.14,-14 46 34.5,15.645,2.488,1.210,24.095,3.365,89.9999,89.9999
25,26.0,19 44 52.32,-14 49 14.6,15.613,1.879,0.747,22.531,0.774,1.488,358.0000
26,27.0,19 44 52.53,-14 48 46.3,15.738,1.800,0.683,23.670,3.689,1.754,362.0000
27,28.0,19 44 52.81,-14 45 28.6,15.802,1.693,0.692,23.447,3.656,1.553,367.0000
28,29.0,19 44 52.82,-14 44 27.8,14.913,1.588,0.575,22.937,3.477,1.426,368.0000
29,30.0,19 44 52.95,-14 46 48.0,15.747,1.724,0.680,22.911,3.090,1.495,373.0000
30,31.0,19 44 52.96,-14 48 00.0,15.020,2.045,0.824,23.419,3.795,1.801,371.0000
31,32.0,19 44 53.05,-14 48 03.2,15.956,1.572,0.554,22.820,2.952,1.248,376.0000
32,33.0,19 44 53.11,-14 48 32.8,15.730,1.735,0.690,23.227,3.287,1.498,378.0000
33,34.0,19 44 53.13,-14 47 49.6,15.711,1.568,0.585,22.649,3.105,1.315,377.0000
34,35.0,19 44 53.14,-14 47 57.5,15.557,1.954,0.782,24.105,4.012,1.788,379.0000
35,36.0,19 44 53.21,-14 49 25.0,15.636,1.676,0.632,24.208,4.176,1.471,382.0000
36,37.0,19 44 53.23,-14 48 35.5,16.250,1.723,0.662,22.494,1.898,89.9999,89.9999
37,38.0,19 44 53.32,-14 44 40.6,16.640,1.666,0.592,22.815,2.102,1.257,385.0000
38,39.0,19 44 53.39,-14 47 48.6,15.852,1.549,0.581,22.651,2.777,1.363,386.0000
39,40.0,19 44 53.54,-14 48 20.7,16.404,1.598,0.666,23.180,2.820,89.9999,89.9999
40,41.0,19 44 53.54,-14 45 59.4,14.603,1.761,0.693,22.661,3.698,1.558,392.0000
41,42.0,19 44 53.64,-14 44 29.6,15.990,1.569,0.572,23.090,3.062,1.379,394.0000
42,43.0,19 44 53.64,-14 48 03.5,16.153,1.563,0.548,23.938,3.340,89.9999,89.9999
43,44.0,19 44 53.73,-14 48 19.1,15.901,1.820,0.784,23.617,3.244,89.9999,89.9999
44,45.0,19 44 53.79,-14 49 31.0,15.920,1.787,0.695,22.490,2.562,1.321,397.0000
45,46.0,19 44 53.81,-14 48 57.0,15.619,1.819,0.714,23.368,3.403,89.9999,89.9999
46,47.0,19 44 53.81,-14 46 59.4,15.840,1.777,0.697,25.359,4.919,1.482,401.0000
47,48.0,19 44 53.86,-14 48 58.3,16.826,1.758,0.762,25.205,4.440,1.45,403.0000
48,49.0,19 44 54.17,-14 43 47.8,17.155,1.538,0.912,22.807,1.129,89.9999,89.9999
49,50.0,19 44 54.24,-14 49 02.7,16.770,1.839,0.691,23.932,2.434,89.9999,89.9999

In [ ]:
Scnd_cat = Kang_2006_2
Main_cat_Coord = SkyCoord(Main_cat['ra'], Main_cat['dec'], unit=(u.hourangle, u.deg))
Scnd_cat_Coord = SkyCoord(Scnd_cat['RAJ2000("h:m:s")'], Scnd_cat['DEJ2000("d:m:s")'], unit=(u.hourangle, u.deg))

In [ ]:
idx, d2D, d3D = Scnd_cat_Coord.match_to_catalog_sky(Main_cat_Coord)

In [ ]:
max_sep = 1.0 * u.arcsec        # Maximum erorr
i_OK = d2D < max_sep

In [ ]:
Secondary_catalog = Scnd_cat[i_OK]
Main_catalog = Main_cat.iloc[idx[i_OK]]

In [ ]:
Secondary_catalog.to_csv(r'Secondary_catalog.csv', header=True, index=None, sep='\t', mode='w')
Main_catalog.to_csv(r'Main_catalog.csv', header=True, index=None, sep='\t', mode='w')

In [ ]:
with open("Main_catalog.csv") as f1, open("Secondary_catalog.csv") as f2, open("X_Catalog.csv", "w") as f3:
     for x, y in zip(f1, f2):
          f3.write(x.strip() + '\t' + y.strip() + '\n')
f1.close()
f2.close()
f3.close()

In [ ]:
X_data = pd.read_csv ("X_Catalog.csv", sep = '\t')
X_data

,mid,Id-main,ra,dec,J,eJ,H,eH,Ks,eKs,...,Seq( ),"RAJ2000(""h:m:s"")","DEJ2000(""d:m:s"")",Kmag(mag),J-K(mag),H-K(mag),gmag(mag),g-i(mag),R-I(mag),[LDB2002]()
0,201,10277,19:44:48.5808,-14:49:04.080,17.35,0.08,16.07,0.09,15.24,0.07,...,1.0,19 44 48.60,-14 49 03.5,16.022,2.141,0.790,23.466,3.443,1.6790,277.0000
1,209,10285,19:44:48.9000,-14:47:37.968,17.33,0.16,16.08,0.11,15.37,0.08,...,2.0,19 44 48.92,-14 47 37.6,15.516,1.793,0.755,24.070,3.889,1.5900,285.0000
2,216,10293,19:44:49.1184,-14:49:51.492,16.79,0.06,15.63,0.05,14.97,0.06,...,3.0,19 44 49.14,-14 49 50.8,15.007,1.833,0.716,23.215,3.857,1.6100,293.0000
3,218,10295,19:44:49.1784,-14:45:46.296,17.79,0.06,16.74,0.06,16.13,0.05,...,4.0,19 44 49.17,-14 45 45.5,16.052,1.623,0.592,22.756,2.512,1.4070,295.0000
4,223,10300,19:44:49.2672,-14:46:35.832,17.35,0.08,16.13,0.05,15.35,0.03,...,5.0,19 44 49.26,-14 46 35.0,15.373,1.914,0.816,23.428,3.440,1.6110,300.0000
5,224,10301,19:44:49.3152,-14:45:00.108,17.49,0.11,16.44,0.07,15.84,0.05,...,6.0,19 44 49.30,-14 44 59.4,15.966,1.591,0.639,23.570,3.341,1.3560,301.0000
6,225,10302,19:44:49.3080,-14:48:46.620,17.38,0.06,16.18,0.05,15.49,0.04,...,7.0,19 44 49.33,-14 48 46.1,15.437,1.947,0.765,23.608,3.603,1.5240,302.0000
7,230,10307,19:44:49.7400,-14:44:42.432,17.08,0.09,16.00,0.06,15.40,0.05,...,8.0,19 44 49.72,-14 44 41.8,15.480,1.646,0.616,23.113,3.369,1.4870,307.0000
8,233,10310,19:44:50.0928,-14:44:39.912,17.42,0.05,16.34,0.06,15.74,0.06,...,9.0,19 44 50.08,-14 44 39.3,15.764,1.571,0.613,23.287,3.292,1.3040,310.0000
9,236,10315,19:44:50.3448,-14:45:36.576,17.91,0.10,16.86,0.08,16.18,0.08,...,10.0,19 44 50.34,-14 45 35.9,16.266,1.786,0.793,23.564,3.371,1.4220,315.0000
10,238,10317,19:44:50.5032,-14:48:47.808,17.66,0.16,16.54,0.12,15.94,0.06,...,11.0,19 44 50.52,-14 48 47.3,15.783,1.599,0.603,22.611,2.851,1.2780,317.0000
11,242,10321,19:44:50.6088,-14:48:55.656,17.42,0.06,16.25,0.10,15.61,0.07,...,12.0,19 44 50.63,-14 48 55.2,15.662,1.818,0.727,22.584,2.705,1.3420,321.0000
12,240,10319,19:44:50.6352,-14:47:34.908,17.96,0.13,16.89,0.11,16.33,0.07,...,14.0,19 44 50.67,-14 47 34.5,16.146,1.604,0.588,22.948,2.784,89.9999,89.9999
13,243,10322,19:44:50.7264,-14:48:41.292,17.18,0.07,16.06,0.04,15.47,0.04,...,15.0,19 44 50.76,-14 48 40.9,15.442,1.708,0.642,22.788,3.105,1.3960,322.0000
14,246,10325,19:44:50.9808,-14:46:28.596,17.24,0.09,16.09,0.08,15.41,0.05,...,16.0,19 44 50.98,-14 46 27.8,15.786,1.781,0.793,22.843,3.247,1.5440,325.0000
15,63,11059,19:44:51.0216,-14:48:05.112,18.38,9.99,16.90,9.99,15.79,9.99,...,17.0,19 44 51.02,-14 48 05.1,16.119,2.734,1.192,23.805,0.044,89.9999,89.9999
16,259,10340,19:44:51.6336,-14:48:34.164,17.42,0.10,16.13,0.05,15.37,0.06,...,18.0,19 44 51.67,-14 48 33.7,15.377,2.096,0.840,24.022,3.760,1.7210,340.0000
17,262,10344,19:44:51.7896,-14:48:49.572,17.55,0.13,16.24,0.11,15.44,0.08,...,19.0,19 44 51.82,-14 48 49.1,15.520,2.046,0.865,23.948,3.660,1.6330,344.0000
18,263,10345,19:44:51.8592,-14:47:46.464,17.33,0.11,16.13,0.07,15.37,0.06,...,20.0,19 44 51.89,-14 47 46.1,15.427,1.866,0.797,24.483,4.282,89.9999,89.9999
19,266,10348,19:44:52.0176,-14:48:40.536,17.38,0.06,16.12,0.03,15.34,0.04,...,22.0,19 44 52.05,-14 48 40.1,15.369,1.912,0.747,23.790,3.622,1.6750,348.0000
20,267,10349,19:44:52.0536,-14:47:48.408,17.51,0.18,16.38,0.14,15.68,0.08,...,24.0,19 44 52.08,-14 47 48.0,15.696,1.830,0.785,23.812,3.794,1.5960,349.0000
21,65,11296,19:44:52.1496,-14:46:35.292,18.37,9.99,16.99,9.99,15.78,9.99,...,25.0,19 44 52.14,-14 46 34.5,15.645,2.488,1.210,24.095,3.365,89.9999,89.9999
22,274,10358,19:44:52.3056,-14:49:15.492,17.41,0.08,16.20,0.08,15.52,0.04,...,26.0,19 44 52.32,-14 49 14.6,15.613,1.879,0.747,22.531,0.774,1.4880,358.0000
23,277,10362,19:44:52.5120,-14:48:46.728,17.52,0.09,16.34,0.06,15.72,0.04,...,27.0,19 44 52.53,-14 48 46.3,15.738,1.800,0.683,23.670,3.689,1.7540,362.0000
24,282,10367,19:44:52.8288,-14:45:29.304,17.55,0.16,16.43,0.12,15.77,0.10,...,28.0,19 44 52.81,-14 45 28.6,15.802,1.693,0.692,23.447,3.656,1.5530,367.0000
25,283,10368,19:44:52.8432,-14:44:28.356,16.76,0.13,15.68,0.10,15.08,0.08,...,29.0,19 44 52.82,-14 44 27.8,14.913,1.588,0.575,22.937,3.477,1.4260,368.0000
26,288,10373,19:44:52.9176,-14:46:47.460,17.90,0.06,17.03,0.04,16.79,0.04,...,30.0,19 44 52.95,-14 46 48.0,15.747,1.724,0.680,22.911,3.090,1.4950,373.0000
27,286,10371,19:44:52.9392,-14:48:00.396,17.02,0.07,15.76,0.05,14.98,0.03,...,31.0,19 44 52.96,-14 48 00.0,15.020,2.045,0.824,23.419,3.795,1.8010,371.0000
28,291,10376,19:44:53.0328,-14:48:03.600,17.39,0.14,16.31,0.06,15.88,0.08,...,32.0,19 44 53.05,-14 48 03.2,15.956,1.572,0.554,22.820,2.952,1.2480,376.0000
29,293,10378,19:44:53.0712,-14:48:33.228,17.44,0.06,16.32,0.04,15.70,0.03,...,33.0,19 44 53.11,-14 48 32.8,15.730,1.735,0.690,23.227,3.287,1.4980,378.0000
30,292,10377,19:44:53.1096,-14:47:49.956,17.32,0.08,16.24,0.04,15.70,0.04,...,34.0,19 44 53.13,-14 47 49.6,15.711,1.568,0.585,22.649,3.105,1.3150,377.0000
31,294,10379,19:44:53.1168,-14:47:57.840,17.30,0.18,16.11,0.13,15.40,0.10,...,35.0,19 44 53.14,-14 47 57.5,15.557,1.954,0.782,24.105,4.012,1.7880,379.0000
32,297,10382,19:44:53.1768,-14:49:25.464,17.25,0.06,16.20,0.07,15.63,0.05,...,36.0,19 44 53.21,-14 49 25.0,15.636,1.676,0.632,24.208,4.176,1.4710,382.0000
33,300,10385,19:44:53.3424,-14:44:41.208,18.39,0.11,17.34,0.08,16.73,0.06,...,38.0,19 44 53.32,-14 44 40.6,16.640,1.666,0.592,22.815,2.102,1.2570,385.0000
34,301,10386,19:44:53.3712,-14:47:48.984,17.53,0.09,16.46,0.07,15.93,0.10,...,39.0,19 44 53.39,-14 47 48.6,15.852,1.549,0.581,22.651,2.777,1.3630,386.0000
35,307,10392,19:44:53.5704,-14:46:00.156,16.47,0.08,15.32,0.06,14.61,0.06,...,41.0,19 44 53.54,-14 45 59.4,14.603,1.761,0.693,22.661,3.698,1.5580,392.0000
36,309,10394,19:44:53.6712,-14:44:30.192,17.69,0.10,16.66,0.05,16.02,0.07,...,42.0,19 44 53.64,-14 44 29.6,15.990,1.569,0.572,23.090,3.062,1.3790,394.0000
37,312,10397,19:44:53.7696,-14:49:31.548,17.51,0.14,16.36,0.08,15.73,0.06,...,45.0,19 44 53.79,-14 49 31.0,15.920,1.787,0.695,22.490,2.562,1.3210,397.0000
38,316,10401,19:44:53.8320,-14:47:00.240,17.56,0.10,16.44,0.05,15.82,0.06,...,47.0,19 44 53.81,-14 46 59.4,15.840,1.777,0.697,25.359,4.919,1.4820,401.0000
39,608,10403,19:44:53.8600,-14:48:58.300,18.70,9.99,17.67,9.99,16.84,9.99,...,48.0,19 44 53.86,-14 48 58.3,16.826,1.758,0.762,25.205,4.440,1.4500,403.0000